export const INI_LISTPHOTO = 'INI_LISTPHOTO';
export const LOADMORE_LISTPHOTO = 'LOADMORE_LISTPHOTO';

export const CHANGE_INFO_PHOTO = 'CHANGE_INFO_PHOTO';

export const CHANGE_TAG_SEARCH = 'CHANGE_TAG_SEARCH';